# Generated by Django 3.1.5 on 2021-03-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ropms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerTables',
            new_name='CustomerTable',
        ),
    ]
