# Generated by Django 3.1.5 on 2021-03-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropms', '0002_auto_20210313_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertable',
            name='status',
            field=models.CharField(choices=[('Occupied', 'Occupied'), ('Unoccupied', 'Unoccupied')], default='Unoccupied', max_length=250),
        ),
    ]
