# Generated by Django 3.1.5 on 2021-03-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropms', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
