# Generated by Django 3.1.5 on 2021-03-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropms', '0005_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=50)),
                ('category', models.CharField(choices=[('Beverages', 'Beverages'), ('Break Fast', 'Break Fast'), ('Desserts', 'Desserts'), ('Family Size', 'Family Size')], default='Beverages', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
