# Generated by Django 3.1.5 on 2021-03-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ropms', '0007_customertable_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertable',
            name='customer',
        ),
    ]
