# Generated by Django 3.1.5 on 2021-03-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ropms', '0009_waiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='ropms.customertable'),
        ),
    ]
