# Generated by Django 3.1.5 on 2021-03-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropms', '0010_auto_20210314_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
