# Generated by Django 3.1.5 on 2021-03-15 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ropms', '0011_customer_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='ropms.customer'),
        ),
    ]
