# Generated by Django 3.1.5 on 2021-03-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropms', '0012_auto_20210315_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Beverages', 'Beverages'), ('Break Fast', 'Break Fast'), ('Desserts', 'Desserts'), ('Vegetables', 'Vegetables'), ('Soup', 'Soup'), ('Salad', 'Salad'), ('Main Course', 'Main Course')], default='Beverages', max_length=50),
        ),
    ]
