# Generated by Django 3.1.5 on 2021-03-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropms', '0015_auto_20210316_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('manu_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
