# Generated by Django 3.1.5 on 2021-03-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ropms', '0016_pos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pos',
            old_name='manu_name',
            new_name='menu_name',
        ),
    ]
