# Generated by Django 3.1.5 on 2021-03-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropms', '0017_auto_20210318_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
    ]
